version: '3.8'

services:
  tattoo_frontend:
    build:
      context: .
      target: deps
    command: yarn dev
    container_name: tattoo-frontend
    networks:
      - frontend
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/.next
      - /app/node_modules

  tattoo_storybook:
    build:
      context: .
      target: deps
    command: yarn storybook
    container_name: tattoo_storybook
    ports:
      - 6006:6006
    volumes:
      - ./:/app
      - /app/node_modules

networks:
  frontend:
    name: 'tattoo-frontend'
