name: Linting workflow
on:
  pull_request:
    branches: [staging]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Node 14
        uses: actions/setup-node@v3.1.0
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint with eslint
        run: yarn lint

      - name: Lint with prettier
        run: yarn format
