name: Run Linter

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]
    

jobs:
  lint:

    runs-on: ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'yarn'
    - run: yarn
    - run: yarn lint
    - run: yarn test
